app_speedtest_index:
    path: /
    controller: App\Controller\SpeedtestController::index
    methods: GET

app_speedtest_days:
    path:
        pt_BR: /{_locale}/dias/{days}
        en: /{_locale}/days/{days}
    controller: App\Controller\SpeedtestController::days
    methods: GET
    defaults:
        _locale: pt_BR
    requirements:
        _locale: en|pt_BR
