FROM php:fpm

RUN apt-get -y update

RUN apt-get install -y libicu-dev zlib1g-dev libpng-dev libjpeg-dev libfreetype6-dev libonig-dev

RUN pecl install redis

RUN docker-php-ext-enable redis

RUN docker-php-ext-configure intl

RUN docker-php-ext-install gd

RUN docker-php-ext-install mbstring

RUN  docker-php-ext-configure pdo_mysql --with-pdo-mysql=mysqlnd

RUN docker-php-ext-install intl pdo pdo_mysql

ADD ./etc/php-fpm/php.ini-production /usr/local/etc/php/php.ini

WORKDIR /app