-- MySQL Script generated by MySQL Workbench
-- Wed Dec 10 09:19:08 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema speedtest
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema speedtest
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `speedtest` ;
USE `speedtest` ;

-- -----------------------------------------------------
-- Table `speedtest`.`server`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `speedtest`.`server` (
  `id` INT NOT NULL,
  `uuid` BINARY(16) NOT NULL,
  `host` VARCHAR(255) NULL,
  `port` INT NULL,
  `name` VARCHAR(60) NULL,
  `location` VARCHAR(60) NULL,
  `country` VARCHAR(60) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  `is_selected` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `speedtest`.`result`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `speedtest`.`result` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `timestamp` TIMESTAMP NOT NULL,
  `ping_jitter` DECIMAL(6,3) NULL,
  `ping_latency` DECIMAL(6,3) NULL,
  `ping_low` DECIMAL(6,3) NULL,
  `ping_high` DECIMAL(6,3) NULL,
  `download_bandwidth` INT NULL,
  `download_bytes` INT NULL,
  `download_elapsed` INT NULL,
  `download_latency_iqm` DECIMAL(6,3) NULL,
  `download_latency_low` DECIMAL(6,3) NULL,
  `download_latency_high` DECIMAL(6,3) NULL,
  `download_latency_jitter` DECIMAL(6,3) NULL,
  `upload_bandwidth` INT NULL,
  `upload_bytes` INT NULL,
  `upload_elapsed` INT NULL,
  `upload_latency_iqm` DECIMAL(6,3) NULL,
  `upload_latency_low` DECIMAL(6,3) NULL,
  `upload_latency_high` DECIMAL(6,3) NULL,
  `upload_latency_jitter` DECIMAL(6,3) NULL,
  `packet_loss` INT NULL,
  `isp` VARCHAR(45) NULL,
  `interface_internal_ip` VARCHAR(45) NULL,
  `interface_name` VARCHAR(45) NULL,
  `interface_mac_addr` VARCHAR(45) NULL,
  `interface_is_vpn` TINYINT NULL,
  `interface_external_ip` VARCHAR(60) NULL,
  `server_id` INT NOT NULL,
  `server_ip` VARCHAR(60) NULL,
  `result_id` VARCHAR(36) NULL,
  `result_url` VARCHAR(255) NULL,
  `result_persisted` TINYINT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_result_server_idx` (`server_id` ASC),
  CONSTRAINT `fk_result_server`
    FOREIGN KEY (`server_id`)
    REFERENCES `speedtest`.`server` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
