#controllers:
#    resource:
#        path: ../src/Controller/
#        namespace: App\Controller
#    type: attribute

app_speedtest_controller:
    resource: "routes/speedtest.yaml"

app_registration_controller:
    resource: "routes/registration.yaml"